spring.application.name=Job-Portal

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/Job_Portal?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=rutavikVS@5120

spring.jpa.hibernate.ddl-auto=update
